spring.application.name=TodoList

spring.datasource.url=jdbc:mysql://172.18.0.2:3306/TodoList
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

jwt.secret=A1aS2s3D4d5F6f7G8g9H1h5K6kLlWwEe
jwt.expiration=3600000